### ISSUE TITLE
Problem in Angular 6

### ISSUE THREAD

**Issue by webnegar** [BioPhoton/angular-signature-pad#2]
Hi, According to  instructions, I did these steps

`ng new app.. (angular6)`

`npm install angular-signature-pad --save`

```
import { AngularSignaturePadModule } from 'angular-signature-pad';

@NgModule({
  imports: [
    ...
    AngularSignaturePadModule.forRoot()
  ]
  ...
})
export class AppModule { }
```
`ng serve
`
but i get this error:

> ERROR in src/app/app.module.ts(5,43): error TS2307: Cannot find module 'angular-signature-pad'.

**Comment by webnegar** [comment]
Any suggestion?

**Comment by mrsavvy** [comment]
I have the same problem.

**Comment by Prasanth-Android** [comment]
i also facing same issue.please help me on this

**Comment by ROHAN-TANDEL** [comment]
is anyone got the fix for above

**Comment by mrsavvy** [comment]
I fixed the problem using the "angular2-signaturepad" https://www.npmjs.com/package/angular2-signaturepad, it works for me.

**Comment by ROHAN-TANDEL** [comment]
But When I try It I got no signature pad on the HTML page.
BTW I am using angular 6 I was thinking some dependencies.
Even My fellow colleague has used this https://www.npmjs.com/package/angular2-signaturepad
It has worked well.

@mrsavvy 
I will give one more try for you suggested option.

**Comment by webappaloosa** [comment]
I'm having the same issue? Has anyone found a solution?

**Comment by webappaloosa** [comment]
The reference forRoot method is picked up by my IDE via the public_api.d.ts file, but i am still getting the following error: 

```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'angular-signature-pad/public_api'
```
maybe needs an index.d.ts ???

**Comment by webnegar** [comment]
finally i fixed this issue by adding source code of module to my project instantly.

add this folder to your shared modules:
angular-signature-pad/src/libs/angular-signature-pad/src/

**Comment by sandisototo** [comment]
> finally i fixed this issue by adding source code of module to my project instantly.
> 
> add this folder to your shared modules:
> angular-signature-pad/src/libs/angular-signature-pad/src/

I don't think this is going to work this means you'll have to do the same for every environment your solution is running.

Any other ideas?

**Comment by Ashveer7** [comment]
A little late but resolved my issues by renaming angular-signature-pad-0.0.13.tgz  to angular-signature-pad-0.0.14.tgz

The package.json in node_modules points to 0.0.14 but the file doesnt exist.

**Comment by ImRehanK** [comment]
The issue is fixed by import module from 'angular-signature-pad/public_api';
But now there is compilation issue:

> ERROR in Error during template compile of 'AppModule'
>   Function calls are not supported in decorators but 'AngularSignaturePadModule' was called.

This Line is causing the error. I don't know what to pass in forRoot(). Any Help:
**AngularSignaturePadModule.forRoot(),**

**Comment by jfrodriguezviamar** [comment]
I got the same issue, i´ve tried all the posted solutions, but none worked for me.

**Comment by takashi1kun** [comment]
> I got the same issue, i´ve tried all the posted solutions, but none worked for me.

Same, i tried every solution posted here and nothing works.
